In [1]:
msg="HelloWorld"
print(msg)

## 打印numpy版本和配置

In [1]:
import numpy as np
print(np.__version__)
np.show_config()

## 创建一个长度为10的0数组

In [2]:
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 创建一个长度为10的0数组，第5个值为1

In [13]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 创建一个值从10到49的数组

In [20]:
import numpy as np
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 反转数组

In [26]:
import numpy as np
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 创建一个从0~8的3*3矩阵

In [31]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 找到非0元素的索引

In [35]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


## 生成一个3*3的对角矩阵

In [38]:
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 生成一个3x3x3的随机数组

In [40]:
import numpy as np
Z = np.random.random((3,3,3))
print(Z)

[[[0.12758823 0.82880138 0.17982751]
  [0.7654287  0.23376065 0.17393362]
  [0.23662742 0.98808821 0.94725096]]

 [[0.67140637 0.2430099  0.26854419]
  [0.55517332 0.47979914 0.10542299]
  [0.82244899 0.79784392 0.49291857]]

 [[0.3597871  0.1905347  0.46924384]
  [0.0810427  0.85308848 0.25714523]
  [0.39937876 0.1333451  0.26367045]]]
