In [1]:
msg="HelloWorld"
print(msg)

## 打印numpy版本和配置

In [1]:
import numpy as np
print(np.__version__)
np.show_config()

## 创建一个长度为10的0数组

In [2]:
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 创建一个长度为10的0数组，第5个值为1

In [3]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 创建一个值从10到49的数组

In [4]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 反转数组

In [5]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


## 创建一个从0~8的3*3矩阵

In [6]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 找到非0元素的索引

In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


## 生成一个3*3的对角矩阵

In [9]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


生成一个3*3*3的随机数组

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.83606893 0.46469431 0.18332864]
  [0.42333863 0.8050822  0.90919621]
  [0.90637568 0.77351304 0.49048782]]

 [[0.40064824 0.8823511  0.19358577]
  [0.68672818 0.95254522 0.47676733]
  [0.04318295 0.84882284 0.82735605]]

 [[0.31706118 0.6215158  0.92592968]
  [0.34897426 0.1762511  0.55837667]
  [0.18850527 0.0028976  0.17412969]]]
